version: "3.9"
services:

  store-locator:
    image: amrkramzy/bol-mancala
    ports:
      - 8989:8989
    environment:
      - DB_JASYPT_ENCRYPTOR_PASSWORD=DB-secret

  store-locator-ui:
    image: amrkramzy/bol-mancala-ui-demo
    ports:
      - 8585:80
    depends_on:
      - store-locator

